### ISSUE TITLE
Essbase Data Input / Structure du flux manquante si aucune ligne trouvée

### ISSUE THREAD

**Issue by lefrancoisbruno** [bcolas/PDIEssbasePlugin#3]
Lorsque l'étape Essbase Data Input ne ramène aucune ligne, elle ne renvoie pas non plus la structure du flux (Message : impossible de trouver le moindre champ lorsqu'on affiche les champs en sortie de l'étape)

La conséquence de ceci est de faire planter la suite du traitement lorsqu'une étape Essbase Data Input ne ramène aucune ligne car les étapes suivantes font référence à des champs qui n'existent pas dans le flux.

Il faudrait que l'étape Essbase Data Input fonction comme les autres étapes d'extraction de données et retourne la structure du flux même si aucune ligne n'a été trouvée.

;-)

**Comment by bcolas** [comment]
Fix with version for Pentaho 8
